### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by happylinks** [thejameskyle/backbone.storage#3]
Hi,
I forked your project and added the possibility to forceFetch a model and to pass options to the collection.
https://github.com/happylinks/backbone.storage/commits/master
Would you be interested in a pullrequest for these features?

**Comment by thejameskyle** [comment]
Sure, open a PR and I'll take a look

**Comment by happylinks** [comment]
PR is created (https://github.com/thejameskyle/backbone.storage/pull/4) :) Closing issue.
